### ISSUE TITLE
msngr.bind(

### ISSUE THREAD

**Issue by puppetMaster3** [KrisSiegel/msngr.js#26]
Hi, you don't say hot to listen to this event, or how to add and listen to dom - or I can't figure it out. Else it looks great.

**Comment by KrisSiegel** [comment]
Hey, so msngr.bind() allows you to use any normal selector to bind HTML elements, events and messages together. So you call it with this signature ```msngr.bind(select, event, message)```. So

```
msngr.bind("input[type=submit]", "click", {
    topic: "Profile",
    category: "Save"
});
```

This will bind the message ```{ topic: "Profile", category: "Save" }``` to all input fields of type "submit" on the "click" event.

Add the dom property and you can have it automatically return values from inputs to the handler of said message via

```
msngr.bind("input[type=submit]", "click", {
    topic: "Profile",
    category: "Save",
    dom: ["input[name=Name]", "input[name=Email]"]}
);
```

Hope that answers your question! I'm working on making the API a little more intuitive in v2 but that's probably another week or two away.

**Comment by puppetMaster3** [comment]
I want to know how to listen to that message that you just showed please. tia

**Comment by KrisSiegel** [comment]
Ah sorry so you listen to a message using ```msngr.on(message, handler)``` or ```msngr.on(topic, category, dataType, handler)```

So in my last example to listen to the message you'd do:
```
msngr.on("Profile", "Save", function (payload) {
    console.log(payload.Name);
    console.log(payload.Email);
});
```

Note: You can omit category or category and dataType from msngr.on(); just a handy shortcut.

**Comment by KrisSiegel** [comment]
I'm going to go ahead and close this but feel free to re-open if I left anything unclear :)

FYI, in the 2.0 API model, my examples turn into the following:

```javascript
msngr("Profile", "Save")
    .bind("input[type=submit]", "click")
    .option("dom", ["input[name=Name]", "input[name=Email]"])
    .on(function (payload) {
        console.log(payload.Name);
        console.log(payload.Email);
    });
```

**Comment by puppetMaster3** [comment]
OK thanks, it works for me.

----- Original Message -----
