### ISSUE TITLE
Node.JS implementation docs required

### ISSUE THREAD

**Issue by amit08255** [KrisSiegel/msngr.js#75]
Please provide an example for Node.JS implementation of this library. Will this library be updated or its support has reached the end of life?

Thank you.

**Comment by KrisSiegel** [comment]
This library is platform agnostic and will run the same examples from the documentation in node as well as the web browser.

As for support well it’s never really had support, it’s just been me and a few groups who use it that I know of have simply never reported any issues with it. I don’t really have plans to continue to support, the last remaining todo items will likely end up closing unless someone else contributes.
